spring:
  datasource:
    ## colocar el puerto que manejan con el gestor de bases de datos y el nombre de la base de datos que crearon para
    ##la app, también se recomienda quitar este comentario para que sea mejor legible el codigo.
    url: jdbc:mariadb://localhost:3307/apirest
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
