spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/apirest
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
